let
    // Appended Batch 1 and Batch 2 data
    Source = Table.Combine({#"Batch 1", #"Batch 2"}),
    // Split Customer Info column with | as delimiter and created Customer Name and Customer ID column
    #"Split Column by Delimiter" = Table.SplitColumn(Source, "Customer Info", Splitter.SplitTextByEachDelimiter({"|"}, QuoteStyle.Csv, false), {"Customer Info.1", "Customer Info.2"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Customer Info.1", type text}, {"Customer Info.2", type text}}),
    #"Capitalized Each Word" = Table.TransformColumns(#"Changed Type",{{"Ship Mode", Text.Proper, type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Capitalized Each Word","calif.","California",Replacer.ReplaceText,{"State"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","TX","Texas",Replacer.ReplaceText,{"State"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","NY","New York",Replacer.ReplaceText,{"State"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Office supply","Office Supplies",Replacer.ReplaceText,{"Category"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Furn","Furniture",Replacer.ReplaceValue,{"Category"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Tech","Technology",Replacer.ReplaceValue,{"Category"}),
    #"Removed Duplicates" = Table.Distinct(#"Replaced Value5"),
    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Duplicates",{{"Order Date", type date}}),
    #"Replaced Value6" = Table.ReplaceValue(#"Changed Type1",null,0,Replacer.ReplaceValue,{"Sales"}),
    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","five",5,Replacer.ReplaceValue,{"Quantity"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7",null,0,Replacer.ReplaceValue,{"Quantity"}),
    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8",null,"Not Specified",Replacer.ReplaceValue,{"Ship Mode"}),
    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9",null,"Blank",Replacer.ReplaceValue,{"State"}),
    #"Replaced Errors" = Table.ReplaceErrorValues(#"Replaced Value10", {{"Order Date", #date(2021, 1, 1)}}),
    #"Added Conditional Column" = Table.AddColumn(#"Replaced Errors", "Column", each if [Product Name] = "Office Chair" then "Furniture" else if [Product Name] = "Desk" then "Furniture" else if [Product Name] = "Laptop" then "Technology" else if [Product Name] = "Monitor" then "Technology" else if [Product Name] = "Notebook" then "Office Supplies" else if [Product Name] = "Pen Set" then "Office Supplies" else if [Product Name] = "Wireless Mouse" then "Technology" else "Null"),
    #"Replaced Value11" = Table.ReplaceValue(#"Added Conditional Column","NaN","Unknown",Replacer.ReplaceText,{"State"}),
    #"Trimmed Text" = Table.TransformColumns(Table.TransformColumnTypes(#"Replaced Value11", {{"Sales", type text}}, "en-US"),{{"Sales", Text.Trim, type text}}),
    #"Replaced Value12" = Table.ReplaceValue(#"Trimmed Text","NaN","0",Replacer.ReplaceText,{"Sales"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value12",{{"Sales", type number}}),
    #"Trimmed Text1" = Table.TransformColumns(Table.TransformColumnTypes(#"Changed Type2", {{"Quantity", type text}}, "en-US"),{{"Quantity", Text.Trim, type text}}),
    #"Replaced Value13" = Table.ReplaceValue(#"Trimmed Text1",12500,125,Replacer.ReplaceValue,{"Sales"}),
    #"Changed Type6" = Table.TransformColumnTypes(#"Replaced Value13",{{"Sales", Currency.Type}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type6",{"Category"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"Order ID", "Customer Info.1", "Customer Info.2", "Order Date", "Ship Mode", "State", "Column", "Product Name", "Sales", "Quantity"}),
    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Column", "Category"}}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns",{{"Quantity", Int64.Type}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type3",{{"Customer Info.1", "Customer Name"}, {"Customer Info.2", "Customer ID"}}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Renamed Columns1",{"Order ID", "Customer ID", "Customer Name", "Order Date", "Ship Mode", "State", "Category", "Product Name", "Sales", "Quantity"}),
    #"Replaced Errors1" = Table.ReplaceErrorValues(#"Reordered Columns1", {{"Quantity", 0}})
in
    #"Replaced Errors1"